version: '3.8'
services:
  package-builder:
    build: .
    volumes:
      - ./cryptobinaryapt:/cryptobinaryapt
      - ./solana-rpc:/solana-rpc
      - ./control.json:/app/control.json

  reverse-proxy:
    image: traefik:v2.8
    command:
      - --api.insecure=true
      - --providers.docker
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.email=info@beardsoft.io
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
    networks:
      - web

  apt-repo:
    image: nginx:alpine
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apt-repo.rule=Host(`apt.beardsoft.io`)"
      - "traefik.http.routers.apt-repo.entrypoints=web"
      - "traefik.http.routers.apt-repo-secure.rule=Host(`apt.beardsoft.io`)"
      - "traefik.http.routers.apt-repo-secure.entrypoints=websecure"
      - "traefik.http.routers.apt-repo-secure.tls.certresolver=myresolver"
    volumes:
      - ./cryptobinaryapt:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - reverse-proxy
    networks:
      - web

# docker network create web
networks:
  web:
    external: true
